README.md, performance_test/helper_scripts/run_experiment.py
I reworked and extended the documentation of the package.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/apexai/performance_test/1)
=> Documentation improvements

performance_test/src/data_running/data_runner_base.hpp
Just a typo that should have seen in code review :p
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/apexai/performance_test/6)
=> fix setup of on_malloc

performance_test/CMakeLists.txt, performance_test/helper_scripts/run_experiment.py, performance_test/src/communication_abstractions/ros2_callback_communicator.hpp, performance_test/src/utilities/rt_enabler.hpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/apexai/performance_test/10)
=> Improve experiment script

performance_test/helper_scripts/performance_test_file_reader.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/apexai/performance_test/12)
=> Improve plotter script

README.md, performance_test/CMakeLists.txt, performance_test/helper_scripts/performance_test_file_reader.py
This simplifies instructions for how to run it and makes moving paths easier.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/apexai/performance_test/14)
=> make the plotting script installable and update README

README.md, performance_test/CMakeLists.txt, performance_test/compile_options.cmake, performance_test/helper_scripts/performance_test_file_reader.py, performance_test/helper_scripts/run_experiment.py, performance_test/package.xml, performance_test/src/communication_abstractions/fast_rtps_communicator.hpp, performance_test/src/communication_abstractions/resource_manager.cpp, performance_test/src/communication_abstractions/ros2_callback_communicator.hpp, performance_test/src/data_running/data_runner.hpp, performance_test/src/data_running/data_runner_base.hpp, performance_test/src/experiment_configuration/experiment_configuration.cpp, performance_test/src/experiment_configuration/topics.hpp, performance_test/src/experiment_execution/analyze_runner.cpp
Locally, `colcon test` is now successful.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/apexai/performance_test/19)
=> Make linters happy

performance_test/helper_scripts/performance_test_file_reader.py
Make it work with ros2 cli tool. #23
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/apexai/performance_test/24)
=> changed shebang line position

README.md, performance_test/helper_scripts/apex_performance_plotter/.gitignore, performance_test/helper_scripts/apex_performance_plotter/.pylintrc, performance_test/helper_scripts/apex_performance_plotter/MANIFEST.in, performance_test/helper_scripts/apex_performance_plotter/README.rst, performance_test/helper_scripts/apex_performance_plotter/apex_performance_plotter/__init__.py, performance_test/helper_scripts/apex_performance_plotter/apex_performance_plotter/template.tex, performance_test/helper_scripts/apex_performance_plotter/requirements.in, performance_test/helper_scripts/apex_performance_plotter/setup.cfg, performance_test/helper_scripts/apex_performance_plotter/setup.py, performance_test/package.xml, performance_test/src/communication_abstractions/connext_dds_micro_communicator.hpp, performance_test/src/communication_abstractions/fast_rtps_communicator.hpp, performance_test/src/communication_abstractions/ros2_callback_communicator.hpp, performance_test/src/data_running/data_runner.hpp, performance_test/src/experiment_configuration/experiment_configuration.cpp, performance_test/src/experiment_configuration/experiment_configuration.hpp, performance_test/src/experiment_execution/analyze_runner.cpp
- Add parsing of environment variables for output to log file
- Add missing dependencies on sensor messages
- Fix style errors found by `ament_*` tools
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/apexai/performance_test/30)
=> Add improved plotter

README.md, performance_test/src/experiment_execution/analyze_runner.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/apexai/performance_test/29)
=> Adding parsing of environment variable to add additional data to the output log file.

README.md, performance_test/CMakeLists.txt, performance_test/src/experiment_configuration/experiment_configuration.cpp
Fixed a small bug were ROS 2 and Connext Micro was not enabled by default.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/apexai/performance_test/33)
=> Regression ros found

performance_test/helper_scripts/run_experiment.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/apexai/performance_test/25)
=> The experiment script can now run multiple performance tests at the same time.

performance_test/helper_scripts/run_experiment.py
@anup-pem: Can you double check that the script I changed still works?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/apexai/performance_test/39)
=> Fixed flake8 errors.

performance_test/src/communication_abstractions/connext_dds_micro_communicator.hpp, performance_test/src/experiment_configuration/experiment_configuration.cpp, performance_test/src/experiment_configuration/experiment_configuration.hpp, performance_test/src/experiment_execution/analysis_result.cpp, performance_test/src/experiment_execution/analyze_runner.cpp, performance_test/src/experiment_execution/analyze_runner.hpp, performance_test/src/utilities/rt_enabler.hpp
Cherry picked  real time related changes from cust_z branch to master
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/apexai/performance_test/38)
=> Cherry-pick real-time related changes from cust_z(e1fbee0296) to master

.gitlab-ci.yml, performance_test/package.xml, performance_test/src/communication_abstractions/connext_dds_micro_communicator.hpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/apexai/performance_test/46)
=> Migrated CI docker image from Bouncy to Crystal.

README.md, performance_test/CMakeLists.txt, performance_test/bin/fastrtpsgen, performance_test/helper_scripts/performance_test_file_reader.py, performance_test/src/communication_abstractions/resource_manager.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/apexai/performance_test/45)
=> Ross desmond ros2 crystal update

performance_test/helper_scripts/apex_performance_plotter/apex_performance_plotter/__init__.py, performance_test/helper_scripts/apex_performance_plotter/apex_performance_plotter/template.tex
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/apexai/performance_test/49)
=> Plotter improvements

performance_test/package.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/apexai/performance_test/63)
=> Use our opensource email address

azure-pipelines.yml, performance_test/package.xml, performance_test/src/communication_abstractions/fast_rtps_communicator.hpp, performance_test/src/communication_abstractions/resource_manager.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/apexai/performance_test/65)
=> Update for Dashing

README.md
Some additional dependencies are required on a plain Ubuntu 18.04 machine.
Adding them to README
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/apexai/performance_test/71)
=> added dependencies

azure-pipelines.yml, tools/Dockerimage.crossbuild, tools/toolchain.cmake
Ready for review
Fixes #78 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/apexai/performance_test/80)
=> crosscompile for arm64

README.md, add_sql_support_readme.md, performance_test/CMakeLists.txt, performance_test/cmake/Modules/FindODB.cmake, performance_test/cmake/Modules/UseODB.cmake, performance_test/design/performance_test-design.md, performance_test/src/experiment_configuration/experiment_configuration.cpp, performance_test/src/experiment_configuration/experiment_configuration.hpp, performance_test/src/experiment_execution/analysis_result.cpp, performance_test/src/experiment_execution/analysis_result.hpp, performance_test/src/experiment_execution/analyze_runner.cpp, performance_test/src/experiment_execution/analyze_runner.hpp, performance_test/src/utilities/statistics_tracker.hpp
The user will be able to additionally save the results into a MySQL, SQLite or PostgreSQL database using odb object-relational mapping for C++. The code can be extended to other types of databases. I haven't check the Postgre database yet, but SQLite and MySQL should work well.
Divya, please go through a code and try it out if it works correctly.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/apexai/performance_test/84)
=> Add possibility to save results into sql database

performance_test/CMakeLists.txt, performance_test/helper_scripts/apex_performance_plotter/apex_performance_plotter/__init__.py, performance_test/helper_scripts/apex_performance_plotter/setup.py, performance_test/helper_scripts/run_experiment.py, performance_test/src/communication_abstractions/resource_manager.cpp, performance_test/src/communication_abstractions/ros2_callback_communicator.hpp, performance_test/src/experiment_configuration/experiment_configuration.cpp
PR open to fulfill [this comment](https://github.com/ApexAI/performance_test/pull/89#issuecomment-543452649). Update FastRTPS usage and allow unregistered options for boost so it doesn't complain about the empty arg that eloquent adds to ros2 launch `--ros-args`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/apexai/performance_test/104)
=> Update to eloquent

performance_test/CMakeLists.txt, performance_test/helper_scripts/apex_performance_plotter/apex_performance_plotter/__init__.py, performance_test/helper_scripts/apex_performance_plotter/setup.py, performance_test/helper_scripts/run_experiment.py, performance_test/src/communication_abstractions/resource_manager.cpp, performance_test/src/experiment_configuration/experiment_configuration.cpp
Reverts ApexAI/performance_test#104
Accidentally added changes to the branch .
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/apexai/performance_test/105)
=> Revert "Update to eloquent"
