ApexAI/performance_test

performance_test/CMakeLists.txt

Avoiding this error:
```
In file included from /perf_test_ws/src/performance_test/performance_test/src/experiment_execution/../data_running/data_runner_factory.hpp:21:0,
from /perf_test_ws/src/performance_test/performance_test/src/experiment_execution/analyze_runner.hpp:23,
from /perf_test_ws/src/performance_test/performance_test/src/experiment_execution/analyze_runner.cpp:15:
/perf_test_ws/src/performance_test/performance_test/src/experiment_execution/../data_running/data_runner_base.hpp: In member function ‘void performance_test::DataRunnerBase::assert_memory_tools_is_working()’:
/perf_test_ws/src/performance_test/performance_test/src/experiment_execution/../data_running/data_runner_base.hpp:107:5: error: ‘osrf_testing_tools_cpp’ has not been declared …
```

adding missing include path for osrf_testing_tools_cpp

---

performance_test/helper_scripts/performance_test_file_reader.py

resolve memory plotting issue
Don't double divide memory usage by 1e3 and don't skip first 10 elements in the table.
follow up to d7e03059e4e9ca23a3e940e354966c6efe725ffa
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/apexai/performance_test/15)

resolve memory plotting issue

---

performance_test/src/experiment_configuration/experiment_configuration.cpp

The check here is inconsistent with the option declared in the command line which means it could never be triggered, and the command line option wouldn't do anything.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/apexai/performance_test/16)

fix the intraprocess flag name

---

performance_test/helper_scripts/policies.yaml
performance_test/helper_scripts/security_setup.sh
performance_test/src/communication_abstractions/resource_manager.cpp
performance_test/src/experiment_configuration/experiment_configuration.cpp
performance_test/src/experiment_configuration/experiment_configuration.hpp

This enables security over ROS2.
Steps to test:
1. Build with flags `-DSECURITY=ON`
2. run the script to enable security
```sh
$ cd performance_test/performance_test/helper_scripts/
$ bash security_setup.sh enable 'ApexOS/apex_ws/demo_keys '
```
3. run the performance test with flag `with_security`, for example
```sh
$ ros2 run performance_test perf_test -c ROS2 -l log -t Array1k --max_runtime 10 --with_security
```
Once the test is done disable the security
```sh
$ cd performance_test/performance_test/helper_scripts/
$ bash security_setup.sh disable
```
Change the `policies.yaml` to diable or enable topics. (for now this only works for 5 performance _test nodes)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …

Security integration

---

performance_test/src/experiment_configuration/experiment_configuration.cpp

Small fix to avoid printing help twice, plus error messages, when running:
`ros2 run performance_test perf_test --help`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/apexai/performance_test/18)

Print help only once

---

performance_test/helper_scripts/performance_test_file_reader.py

In case X11 is not enabled and without users to configure Matplotlib, use agg backend as default. #21
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/apexai/performance_test/22)

allow users to generate .pdf result file without running X server

---

README.md
performance_test/src/communication_abstractions/connext_dds_micro_communicator.hpp
performance_test/src/communication_abstractions/fast_rtps_communicator.hpp
performance_test/src/communication_abstractions/ros2_callback_communicator.hpp
performance_test/src/data_running/data_runner.hpp
performance_test/src/experiment_configuration/experiment_configuration.cpp
performance_test/src/experiment_configuration/experiment_configuration.hpp

This patch adds a round trip mode to enable performance testing between machines without worrying about synchronizing clocks.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/apexai/performance_test/26)

Added roundtrip mode.

---

performance_test/CMakeLists.txt

fatal error: fastrtps/participant/Participant.h: No such file or directory
fatal error: fastrtps/TopicDataType.h: No such file or directory
The build fails due to incorrect include directory. "fastrtps/include" is
already part of FastRTPS_INCLUDE_DIR, no need to append.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/apexai/performance_test/27)

Fix build error due to missing includes

---

performance_test/src/communication_abstractions/fast_rtps_communicator.hpp

This PR fixes a configuration issue on the communications abstraction for FastRTPS.
When using KEEP_LAST, resourceLimitsQos should be greater or equal than the history depth.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/apexai/performance_test/55)

Fixed keep_last on FastRTPS

---

performance_test/src/data_running/data_runner_base.hpp

Checking `PERFORMANCE_TEST_MEMORYTOOLS_ENABLED` before defining `assert_memory_tools_is_working`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/apexai/performance_test/52)

Fix build error if osrf_testing_tools_cpp not found

---

performance_test/src/experiment_configuration/experiment_configuration.cpp

This PR turns `use_drive_px_rt` argument into two new arguments `use_rt_prio` and `use_rt_cpus`. It keeps the old argument as an alias to be backward compatible.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/apexai/performance_test/64)

Allowing configuration of RT priority and cpus.

---

performance_test/helper_scripts/generate_apex_xml.py
performance_test/src/communication_abstractions/resource_manager.cpp
performance_test/src/communication_abstractions/resource_manager.hpp

To be able to limit the network interfaces used for the communication during the test runs, an interfaces whitelist is loaded from a XML configuration file with the default name. This file is generated with generate_apex_xml.py, passing a list of ip address and a destination to it. The resulting file needs to be placed on the directory from where the tests are run. If PERFORMANCE_TEST_FASTRTPS_ENABLED is set to true, resource_manage.cpp loads the participant attributes specified in the XML file using eProsima xmlparser to get the whitelist.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/apexai/performance_test/69)

generate and load default XML file to configure whitelists

---

README.md
performance_test/CMakeLists.txt
performance_test/design/performance_test-design.md
performance_test/src/communication_abstractions/ros2_callback_communicator.hpp
performance_test/src/communication_abstractions/ros2_communicator.hpp
performance_test/src/communication_abstractions/ros2_waitset_communicator.hpp
performance_test/src/data_running/data_runner_factory.cpp
performance_test/src/experiment_configuration/communication_mean.hpp
performance_test/src/experiment_configuration/experiment_configuration.cpp

Added polling subscription plugin for ROS 2 to the performance test. It can be used by specifying the argument `-c [ --communication ]` arg  Communication plugin to use as `ROS2PollingSub` when running performance test . 
To turn on the option for using Polling Subscription Plugin we need to compile the performance test with cmake args `PERFORMANCE_TEST_POLLING_SUBSCRIPTION_ENABLED` and value as `ON`  :
```bash
colcon build --cmake-clean-cache --cmake-args -DPERFORMANCE_TEST_POLLING_SUBSCRIPTION_ENABLED=ON
```
Sample usage for the plugin can be :
```bash
ros2 run performance_test perf_test -c ROS2PollingSubscription -l log -t Array16k --history_depth 100 --max_runtime 60 -p 1 -s 1 -r 20 --reliable --keep_last`
```
I have verified that this plugin builds and runs successfully on ApexOS …

ROS2 Polling Subscription Plugin

---

performance_test/CMakeLists.txt
performance_test/helper_scripts/apex_performance_plotter/apex_performance_plotter/__init__.py
performance_test/include/performance_test/version.h
performance_test/src/experiment_configuration/experiment_configuration.cpp
performance_test/version_check.bash

- Bake performance_test into the perf_test EXE so it can show up as part of the report
- Have the perf_plot tool recognize the version and print it in the "test setup" section of the report
- Remove duplciate QOS settings from the 'test setup' section of the report
I also tested what happens if you blow away the .git directory and build performance_test.  The tool will still build, but the version shows up as blank.
Here is a report generated with the changes in this PR:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/apexai/performance_test/93)

Record version hash

---

tools/toolchain.cmake

Make it possible to use other SYSROOTs other than `/sysroot`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/apexai/performance_test/95)

Allow use of another SYSROOT

---

tools/toolchain_arm.cmake

- The github CI job expects to copy ROS binaries into the sysroot directory
- toolchain_arm.cmake works with CI that doesn't do this step
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/apexai/performance_test/101)

Add a toolchain that doesn't require copying artifacts to sysroot

---

performance_test/helper_scripts/apex_performance_plotter/apex_performance_plotter/__init__.py
performance_test/include/performance_test/version.h
performance_test/src/experiment_configuration/experiment_configuration.cpp
performance_test/src/experiment_configuration/experiment_configuration.hpp

This calls the `rmw.h` function `rmw_get_implementation_identifier` so the resulting graph of the test results can include the RMW implementation.
[log_Array1k_11-10-2019_10-58-42.pdf](https://github.com/ApexAI/performance_test/files/3719017/log_Array1k_11-10-2019_10-58-42.pdf)
In the attached report, notice that the information is included in the `environment` section in the lower-right
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/apexai/performance_test/97)

Print RMW implementation in log

---

performance_test/src/experiment_configuration/experiment_configuration.cpp

See https://github.com/ApexAI/performance_test/pull/97#issuecomment-542323712 for background
This check_setup was causing `perf_test --help` to fail with a non-zero exit code
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/apexai/performance_test/103)

Don't error out on --help

---

performance_test/CMakeLists.txt
performance_test/helper_scripts/apex_performance_plotter/apex_performance_plotter/__init__.py
performance_test/helper_scripts/apex_performance_plotter/apex_performance_plotter/generate_plots.py
performance_test/src/experiment_execution/analysis_result.cpp
performance_test/src/experiment_execution/analysis_result.hpp
performance_test/src/experiment_execution/analyze_runner.cpp
performance_test/src/experiment_execution/analyze_runner.hpp
performance_test/src/utilities/cpu_usage_tracker.hpp

This PR contains changes to :
1. Compute the %CPU load for the experiments running as part of performance test 
2. Add a new column in performance test results csv called `cpu usage(%)` logging the cpu load.
3. Plot the CPU usage along with printing the average load seen during the experiment as part of the pdf generated.
The new column added can be seen in the screenshot below with the load values logged throughout the experiment run:
The `cpu usage(%)` is seen as part of the generated pdf on the usage graph on the right plotted as a blue line and also a new field called `cpu usage(%)` is seen as part of `average results` section of the report.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …

Compute cpu load % for running experiments and log in the result csv and generated plots

---

performance_test/src/experiment_execution/analysis_result.hpp
performance_test/src/utilities/cpu_usage_tracker.hpp

After creating a separate class `CpuInfo`, we need to add this class as a `odb::friend` to see the values in the database. Here I add small fixes that enable saving cpu info data into a database.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/apexai/performance_test/106)

Fix error in odb after adding cpu_info

---

performance_test/CMakeLists.txt
performance_test/env_hook/odb_library_path.sh.in

- Do this automatically when setup.sh is sourced
- Ideally we'd provide a ROS wrapper package for ODB, but I this is maybe OK too
Prior to this change, if you built with ODB support, you'd have to manually add the odb lib directory to your LD_LIBRARY_PATH before perf_test would run.  The error was something like
```
/opt/PerformanceTest/lib/performance_test/perf_test: error while loading shared libraries: libodb-2.5.0-b.15.so: cannot open shared object file: No such file or directory
```
After this change, sourcing /opt/PerformanceTest/setup.bash is enough
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/apexai/performance_test/109)

Have performance_test add the path to ODB to env
